Add block/unblock/remove APIs.
riscv-non-isa/riscv-ap-tee pull request #24
Opened 2023-04-06 11:57 UTC by rajnesh-kanwal

2023-04-06 19:46 UTC, rsahita commented on specification/sbi_atee.adoc
general comment - the "block" terminology may be confusing - I have been using "invalidate page mapping" and "validate page mapping" terms - perhaps we can use the same for these ABI functions.

2023-04-06 19:47 UTC, rsahita commented on specification/sbi_atee.adoc
> +. `sbi_tee_host_tvm_block_pages()`
```suggestion
. `sbi_tee_host_tvm_invalidate_page_maps()`
```

2023-04-06 19:48 UTC, rsahita commented on specification/sbi_atee.adoc
> +[#sbi_tee_host_tvm_block_pages]
```suggestion
[#sbi_tee_host_tvm_invalidate_page_maps]
```

2023-04-06 19:48 UTC, rsahita commented on specification/sbi_atee.adoc
> +=== Function: TEE Host TVM Block Pages (FID #16)
```suggestion
=== Function: TEE Host TVM Invalidate Page Mappings (FID #16)
```

2023-04-06 19:49 UTC, rsahita commented on specification/sbi_atee.adoc
> +struct sbiret sbi_tee_host_tvm_block_pages(unsigned long tvm_guest_id,
```suggestion
struct sbiret sbi_tee_host_tvm_invalidate_page_maps(unsigned long tvm_guest_id,
```

2023-04-06 19:49 UTC, rsahita commented on specification/sbi_atee.adoc
> +Invalidates the pages in the specified range of guest physical address space and
```suggestion
Invalidates the page mappings in the specified range of guest physical address space and
```

2023-04-06 19:50 UTC, rsahita commented on specification/sbi_atee.adoc
> +marks the pages as blocked.
```suggestion
thus marks the pages as blocked from creating new cached mappings.
```

2023-04-06 19:51 UTC, rsahita commented on specification/sbi_atee.adoc
> +marks the pages as blocked. The host must complete a TVM TLB invalidation sequence,
```suggestion
marks the pages as not-present. The host must complete a TVM TLB invalidation sequence,
```

2023-04-06 19:51 UTC, rsahita commented on specification/sbi_atee.adoc
> +Guest page faults taken by the TVM on blocked pages continue to be reported to the host.
```suggestion
Guest page faults taken by the TVM on invalid page mappings continue to be reported to the host.
```

2023-04-06 19:51 UTC, rsahita commented on specification/sbi_atee.adoc
> +The page remains invalid until the mapping is unblocked (marked present) removed, or
```suggestion
The page mapping remains invalid until the mapping is unblocked (marked present) removed, or
```

2023-04-06 19:52 UTC, rsahita commented on specification/sbi_atee.adoc
> +[#table_sbi_tee_host_tvm_block_pages_errors]
```suggestion
[#table_sbi_tee_host_tvm_invalidate_page_maps_errors]
```

2023-04-06 19:52 UTC, rsahita commented on specification/sbi_atee.adoc
> +.TEE Host TVM Block Pages
```suggestion
.TEE Host TVM Invalidate Page Mappings
```

2023-04-06 19:53 UTC, rsahita commented on specification/sbi_atee.adoc
> +[#sbi_tee_host_tvm_unblock_pages]
can you please make similar changes for the unblock_pages -> validate_page_maps

2023-04-06 19:54 UTC, rsahita requested changes
LGTM - only change requested is to use the term "Invalidate page mappings" instead of "block pages" (and vice-versa).

2023-04-11 12:14 UTC, rajnesh-kanwal commented on specification/sbi_atee.adoc
Adding @abrestic-rivos to provide his input, as he designed these APIs.

2023-04-11 12:23 UTC, abrestic-rivos commented on specification/sbi_atee.adoc
I'm fine with the rename. My only complaint with the "invalidate/validate page mappings" is it's a bit verbose. How about `{in,}validate_ptes` or `{in,}validate_pages` or `set_ptes_{present,invalid}`, etc.

2023-04-11 14:37 UTC, rajnesh-kanwal commented on specification/sbi_atee.adoc
`{in,}validate_pages` SGTM.

2023-04-13 21:28 UTC, rsahita approved these changes

2023-04-13 21:28 UTC, merged